# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 20:19
from __future__ import unicode_literals

from django.db import migrations, models
import osmaxx.conversion.models


class Migration(migrations.Migration):

    dependencies = [
        ('conversion', '0002_auto_20160310_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='resulting_file',
            field=models.FileField(max_length=250, null=True, upload_to=osmaxx.conversion.models.job_directory_path, verbose_name='resulting file'),
        ),
    ]
