# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-30 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversion', '0005_auto_20160613_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='estimated_pbf_size',
            field=models.FloatField(null=True, verbose_name='estimated pbf size in bytes'),
        ),
        migrations.AddField(
            model_name='job',
            name='extraction_duration',
            field=models.DurationField(help_text='time needed to generate the extraction', null=True, verbose_name='extraction duration'),
        ),
        migrations.AddField(
            model_name='job',
            name='unzipped_result_size',
            field=models.FloatField(help_text='without the static files, only the conversion result', null=True, verbose_name='file size in bytes'),
        ),
    ]
