# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-01 11:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversion', '0006_auto_20160630_1355'),
        ('conversion', '0006_rename_pseudo-mercator_choice'),
    ]

    operations = [
    ]
