# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversion', '0007_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='queue_name',
            field=models.CharField(choices=[('high', 'high'), ('default', 'default')], default='default', help_text='queue name for processing', max_length=50, verbose_name='queue name'),
        ),
    ]
