# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 08:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversion', '0008_job_queue_name'),
        ('conversion', '0008_rename_ESRI_to_Esri'),
    ]

    operations = [
    ]
