# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversion', '0009_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='queue_name',
            field=models.CharField(choices=[('default', 'default'), ('high', 'high')], default='default', help_text='queue name for processing', max_length=50, verbose_name='queue name'),
        ),
        migrations.AlterField(
            model_name='parametrization',
            name='detail_level',
            field=models.IntegerField(choices=[(120, 'Full detail'), (60, 'Simplified')], default=120, verbose_name='detail level'),
        ),
    ]
