# Generated by Django 3.2.6 on 2021-08-19 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversion', '0013_auto_20170712_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='parametrization',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='parametrization',
            name='out_srs',
            field=models.IntegerField(blank=True, choices=[(4326, 'WGS 84'), (3857, 'Pseudo-Mercator'), (4322, 'WGS 72'), (4269, 'NAD 83'), (4277, 'OSGB 36')], default=4326, help_text='EPSG code of the output spatial reference system', null=True, verbose_name='output SRS'),
        ),
    ]
