# Generated by Django 3.2.6 on 2021-08-26 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversion', '0014_auto_20210819_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='callback_url',
            field=models.CharField(max_length=250, verbose_name='callback url'),
        ),
    ]
