# Generated by Django 3.2.6 on 2021-08-27 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversion', '0015_alter_job_callback_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='callback_url',
        ),
        migrations.RemoveField(
            model_name='job',
            name='own_base_url',
        ),
    ]
