language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"

cache: pip

sudo: required

env:
    - TOX_ENV=quick-tests
    - TOX_ENV=flake8
    - TOX_ENV=slow-tests

matrix:
  fast_finish: true

services:
  - docker
  - redis-server

before_install:
  - docker pull geometalab/postgis-with-translit
  - docker run -d -p "127.0.0.1:65432:5432" -e POSTGRES_DB='osmaxx_db' --name pg_translit geometalab/postgis-with-translit
  - docker run -d -p "127.0.0.1:54321:5432" -e POSTGRES_DB='postgres' --name pg_tests geometalab/postgis-with-translit
  - docker ps -a
  - sleep 10

install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libspatialite-dev sqlite3 libsqlite3-dev binutils libproj-dev gdal-bin
  - pip install tox

script:
    - tox -e $TOX_ENV
