databasebase:
  image: geometalab/postgis:9.4

base:
  build: .
  environment:
    # port and host application listens
    - APP_PORT=8000
    - APP_HOST=0.0.0.0

    # hardened security compared to default settings.
    - DJANGO_SECURE_BROWSER_XSS_FILTER=true
    - DJANGO_SECURE_CONTENT_TYPE_NOSNIFF=true
    - DJANGO_LOG_LEVEL=INFO

# All the settings below this line shouldn't need a change in development
##########################################################################
    # shared data
    - DJANGO_STATIC_ROOT=/data/static
    - DJANGO_MEDIA_ROOT=/data/media
    - DJANGO_PRIVATE_MEDIA_ROOT=/data/private_media
    - DJANGO_DATABASE_URL=postgis://postgres@database/postgres

    # Logging
    - PYTHONUNBUFFERED=non-empty-string
    - PYTHONIOENCODING=utf-8

    # We enable Python hash randomization to protect Django from certain DoS attacks.
    # See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/#python-options
    - PYTHONHASHSEED=random

conversionenvironment:
  environment:
    - DJANGO_DEBUG=true

    # hardened security compared to default settings.
    - DJANGO_SECURE_BROWSER_XSS_FILTER=true
    - DJANGO_SECURE_CONTENT_TYPE_NOSNIFF=true
    - DJANGO_LOG_LEVEL=ERROR

    # Logging
    - PYTHONUNBUFFERED=non-empty-string
    - PYTHONIOENCODING=utf-8
    - LC_ALL=C.UTF-8
    - LANG=C.UTF-8

    # We enable Python hash randomization to protect Django from certain DoS attacks.
    # See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/#python-options
    - PYTHONHASHSEED=random

    # port and host application listens
    - APP_PORT=8901
    - APP_HOST=0.0.0.0

    # shared data
    - DJANGO_STATIC_ROOT=/data/static
    - DJANGO_MEDIA_ROOT=/data/media
    - DJANGO_DATABASE_URL=postgis://postgres@database/postgres

    # shared result dir
    - OSMAXX_CONVERSION_SERVICE_RESULT_DIR=/data/results

    # shared pbf planet file - needs to be the same as
    #    `osmplanet`: osm_planet_mirror + osm_planet_path_relative_to_mirror
    - OSMAXX_CONVERSION_SERVICE_PBF_PLANET_FILE_PATH=/var/data/osm-planet/switzerland-latest.osm.pbf
    - DJANGO_SETTINGS_MODULE=conversion_service.config.settings.worker
