shareddata:
  image: buildpack-deps:jessie
  command: /bin/true
  volumes:
    # as noted in https://docs.docker.com/userguide/dockervolumes/#mount-a-host-file-as-a-data-volume
    # the parent directory should be mounted, not the directories itself
    # otherwise we get OSError: Device or resource busy
    - /data
    # database
    - /database/data
    # temporary results directory used as pipe between multiple docker forests
    - /tmp/osmaxx-results:/results
    # emails file from email sending during development and testing
    - /tmp/osmaxx-development-emails:/dev-emails
  net: "none"

sources:
  image: buildpack-deps:jessie
  volumes:
    - ./web_frontend:/home/osmaxx/source

webapp:
  extends:
    file: compose-common.yml
    service: base
  command: honcho start -f Procfile.django.dev
  ports:
    - "8000:8000"
  expose:
    - "8000"
  volumes_from:
    - sources
    - shareddata
  links:
    - databasedev:database
    - conversionservice:conversionservice
    # only needed to have a worker up and running
    - conversionworker:conversionworker
  environment:
    - DJANGO_SETTINGS_MODULE=config.settings.local
    - DJANGO_DEBUG=true
    - DJANGO_SERVER_EMAIL=osmaxx-srv@localhost
    - DJANGO_DEFAULT_FROM_EMAIL=osmaxx@localhost
    - OSMAXX_ACCOUNT_MANAGER_EMAIL=user-manager@localhost
    - DJANGO_EMAIL_FILE_PATH=/dev-emails
    - DJANGO_EMAIL_BACKEND=django.core.mail.backends.filebased.EmailBackend
    - DJANGO_SECRET_KEY=my.secret.key.is.not.secret!
    # should correspond to link defined under `links`
    - DJANGO_OSMAXX_CONVERSION_SERVICE_URL=http://conversionservice:8901/api/
    # corresponds to `conversionservice`: SERVICE_USER_NAME
    - DJANGO_OSMAXX_CONVERSION_SERVICE_USERNAME=dev
    # corresponds to `conversionservice`: SERVICE_USER_PASSWORD
    - DJANGO_OSMAXX_CONVERSION_SERVICE_PASSWORD=dev

databasedev:
  extends:
    file: compose-common.yml
    service: databasebase
  volumes_from:
    - shareddata
  environment:
    - PGDATA=/database/data

######## CONVERSION SERVICE ###########
conversionworker:
  extends:
    file: compose-common.yml
    service: conversionenvironment
  image: geometalab/osmaxx-conversion-worker
  command: [honcho, -f, ./conversion_service/worker/Procfile, start]
  volumes_from:
    - conversionservicedata
  links:
    - conversionserviceredis:redis

conversionservice:
  extends:
    file: compose-common.yml
    service: conversionenvironment
  image: geometalab/osmaxx-conversion-service
  command: [honcho, -f, ./conversion_service/Procfile.dev, start]
  ports:
    - "8901:8901"
  expose:
    - "8901"
  volumes_from:
    - conversionservicedata
  links:
    - conversionserviceredis:redis
    - conversionservicepostgres:database
  environment:
    - DJANGO_SETTINGS_MODULE=conversion_service.config.settings.local
    # needs to be the same as `DJANGO_OSMAXX_CONVERSION_SERVICE_USERNAME` in `webapp`
    - SERVICE_USER_NAME=dev
    # needs to be the same as `DJANGO_OSMAXX_CONVERSION_SERVICE_PASSWORD` in `webapp`
    - SERVICE_USER_PASSWORD=dev

conversionservicedata:
  image: debian:jessie
  command: echo true
  volumes:
    - /data/results
    - /tmp/osm-planet/:/var/data/osm-planet

osmplanet:
  image: geometalab/osm-planet
  volumes_from:
    - conversionservicedata
  environment:
    - osm_planet_mirror=http://download.geofabrik.de/europe/
    - osm_planet_path_relative_to_mirror=switzerland-latest.osm.pbf

conversionserviceredis:
  image: redis

conversionservicepostgres:
  image: geometalab/postgis:9.4
