version: '3.7'
# for local development

# to run python tests:
# docker-compose run --rm -e DJANGO_SETTINGS_MODULE=config.settings.tests django  python manage.py test

# setup project locally (migrations and static files):
# docker-compose run --rm frontend ./manage.py migrate --noinput
# docker-compose run --rm frontend ./manage.py collectstatic --noinput
# docker-compose run --rm mediator ./manage.py migrate --noinput
# docker-compose run --rm mediator ./manage.py collectstatic --noinput

services:

  access-rights:
    image: ubuntu:latest
    command: bash -c 'chown -R 1000 /access'
    user: root
    volumes:
      - frontend-media:/access/media
      - worker-data:/access/job_result_files
      - worker-data-ignored:/access/ignored-worker
    logging: &logging
      driver: json-file
      options:
        max-size: 50m

  proxy:
    image: geometalab/env-configurable-caddy:latest
    environment:
      # See https://caddyserver.com/docs/quick-starts/caddyfile for details
      CADDY_CONFIG: |
        :8080 {
          route {
            reverse_proxy /api* {
              to frontend:8000
            }
            reverse_proxy /admin* {
              to frontend:8000
            }
            handle /media/* {
              uri strip_prefix /media
              file_server /* {
                root /data/frontend/
                browse
              }
            }
            reverse_proxy /* {
              to frontend:8000
            }
          }
        }
    volumes:
      - frontend-media:/data/media
      - worker-data:/data/media/job_result_files
    ports:
    - 0.0.0.0:8080:8080/tcp
    networks:
      - default
    logging:
      <<: *logging
  ##### frontend START ########
  frontend: &frontend
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
    entrypoint: dockerize -wait tcp://frontenddatabase:5432
    command: ./manage.py runserver_plus 0.0.0.0:8000
    user: "1000"
    volumes:
      - ./osmaxx:/home/py/osmaxx/osmaxx
      - ./web_frontend:/home/py/osmaxx/web_frontend
      - frontend-media:/data/media
      - worker-data:/data/media/job_result_files
    environment:
      - DJANGO_ALLOWED_HOSTS=*
      - DJANGO_SECRET_KEY=insecure!1
      - DJANGO_SETTINGS_MODULE=config.settings.local
      - DJANGO_DEBUG=true
      # set the following two lines if you want to be able to log in using OSM
      # but don't commit them!
      - SOCIAL_AUTH_OPENSTREETMAP_KEY=
      - SOCIAL_AUTH_OPENSTREETMAP_SECRET=
#     Allow access from any private-use IP, since docker assigns "random" IPs.
#     172.*.*.* is actually allowing too much, but this docker-compose file should
#     only ever be used on local development machine, anyway!
      - DJANGO_INTERNAL_IPS=172.*.*.*,10.*.*.*,192.168.*.*,127.0.0.1,${PUBLIC_LOCALHOST_IP:-192.168.2.1}
      - DJANGO_DEFAULT_FROM_EMAIL=webmaster@osmaxx.exmaple.com
      - DJANGO_SERVER_EMAIL=webmaster@osmaxx.exmaple.com
      - OSMAXX_ACCOUNT_MANAGER_EMAIL=webmaster@osmaxx.exmaple.com
      - DJANGO_LOG_LEVEL=INFO
      - DJANGO_EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend
      - DJANGO_CSRF_COOKIE_SECURE=false
      - DJANGO_SESSION_COOKIE_SECURE=false
      - DJANGO_DATABASE_URL=postgis://frontend:insecureChangeInProduction!@frontenddatabase/frontend
    networks:
      - default
    logging:
      <<: *logging
  frontend-purge-files:
    <<: *frontend
    command: ./manage.py purge_expired_result_files
  frontenddatabase:
    image: postgis/postgis:13-3.1
    volumes:
      - frontend-database-data:/database/data
    environment:
      - PGDATA=/database/data
      - POSTGRES_DB=frontend
      - POSTGRES_USER=frontend
      - POSTGRES_PASSWORD=insecureChangeInProduction!
    networks:
      - default
    logging:
      <<: *logging
  ##### frontend END ########
  ##### CONVERSION SERVICE START ########
  mediator: &mediator
    build:
      context: .
      dockerfile: Dockerfile
      target: mediator
    user: "1000"
    networks:
      - default
    volumes:
      - ./osmaxx:/home/py/osmaxx/osmaxx
      - ./web_frontend:/home/py/osmaxx/web_frontend
      - ./conversion_service:/home/py/osmaxx/conversion_service
      - worker-data-ignored:/data
      - worker-data:/data/media/job_result_files
    command: ./manage.py runserver_plus 0.0.0.0:8901
    environment:
      - DJANGO_ALLOWED_HOSTS=*
      - DJANGO_SECRET_KEY=insecure!2
      - DJANGO_SETTINGS_MODULE=conversion_service.config.settings.local
      - DJANGO_DEBUG=true
      - DJANGO_LOG_LEVEL=INFO
      - DJANGO_DATABASE_URL=postgis://mediator:insecureChangeInProduction!@mediatordatabase/mediator
    networks:
      - default
    logging:
      <<: *logging
  harvester:
    <<: *mediator
    command: ./manage.py result_harvester
  mediatordatabase:
    image: postgis/postgis:13-3.1
    volumes:
      - mediator-database-data:/database/data
    environment:
      - PGDATA=/database/data
      - POSTGRES_DB=mediator
      - POSTGRES_USER=mediator
      - POSTGRES_PASSWORD=insecureChangeInProduction!
    networks:
      - default
    logging:
      <<: *logging
  worker: &worker
    build:
      context: .
      dockerfile: Dockerfile
      target: worker
    command: ./manage.py rqworker default
    volumes:
      - ./osmaxx:/home/py/osmaxx/osmaxx
      - ./web_frontend:/home/py/osmaxx/web_frontend
      - ./conversion_service:/home/py/osmaxx/conversion_service
      - osm_data:/var/data/osm-planet
      - worker-data:/data/media/job_result_files
    environment:
      - DJANGO_SECRET_KEY=insecure!3
    networks:
      - default
    logging:
      <<: *logging
  worker-exclusive:
    <<: *worker
    command: ./manage.py rqworker high
    environment:
      - DJANGO_SECRET_KEY=insecure!4
      - GIS_CONVERSION_DB_USER=worker
      - GIS_CONVERSION_DB_PASSWORD=worker
      # ATTENTION: db name needs to be different
      # to the one defined in the worker-db
      - GIS_CONVERSION_DB_NAME=osmaxx-temp-db
      - GIS_CONVERSION_DB_HOST=worker-db
  worker-db:
    build:
      context: docker-helper-images/osmaxx-postgis-translit/
      dockerfile: Dockerfile
    volumes:
      - worker-db:/database/data
    environment:
      - PGDATA=/database/data
      - POSTGRES_DB=worker
      - POSTGRES_USER=worker
      - POSTGRES_PASSWORD=worker
    ports:
      - "5432:5432"
  conversionserviceredis:
    image: redis
    networks:
      - default
    logging:
      <<: *logging
  ##### CONVERSION SERVICE END ########
  ##### WORLD PBF UPDATER START ########
  osm-pbf-updater:
    build:
      context: docker-helper-images/osm_pbf_updater/
      dockerfile: Dockerfile
    volumes:
      - osm_data:/var/data/osm-planet
    entrypoint: /bin/bash
    command: /opt/development_download_only.sh
    # these are just examples
    # environment:
    # - osmupdate_extra_params=--base-url=download.geofabrik.de/europe/switzerland-updates/
    # - osm_planet_mirror=http://download.geofabrik.de/
    # - osm_planet_path_relative_to_mirror=europe/switzerland-latest.osm.pbf
    networks:
      - default
    logging:
      <<: *logging
  ##### WORLD PBF UPDATER END ########
  ##### OSM-BOUNDARIES START ######
  osmboundaries-database:
    # to limit scaling to exactly 1, we need to specify the container name
    image: postgis/postgis:13-3.1
    volumes:
      - osmboundaries-postgis-data:/var/lib/postgresql
    command: postgres -B 1GB -F -S 1GB
    # command: postgres -B 2GB -F -N 512 -S 2GB
    environment:
      - POSTGRES_DB=osmboundaries
      - POSTGRES_USER=osmboundaries
      - POSTGRES_PASSWORD=osmboundaries
    networks:
      - default
    logging:
      <<: *logging
  osmboundaries-importer:
    # to limit scaling to exactly 1, we need to specify the container name
    container_name: osmboundaries_importer
    image: geometalab/osmboundaries:latest
    depends_on:
      - osmboundaries-database
    environment:
        # the same as the ones in the database above
        - POSTGRES_DB=osmboundaries
        - POSTGRES_USER=osmboundaries
        - POSTGRES_PASSWORD=osmboundaries
        # same as the link name/depends_on
        - POSTGRES_HOST=osmboundaries-database
    networks:
      - default
    logging:
      <<: *logging
  ##### OSM-BOUNDARIES END ######
volumes:
  # osmaxx
  frontend-database-data: {}
  frontend-media: {}
  mediator-database-data: {}
  worker-data: {}
  worker-data-ignored: {}
  worker-db: {}
  osm_data: {}
  database-postgis-data: {}
  osmboundaries-postgis-data: {}
