webappsource:
    build: webappdata
# until https://github.com/docker/docker/pull/12648 is resolved, we can't use
# user namespaces properly
#    user: osmaxx
    volumes:
        - webapp/osmaxx:/home/osmaxx/osmaxx/

database:
    build: database
    user: postgres

webapp:
    build: webapp
    # on production, enable the following
    # command: gunicorn -b 0.0.0.0:8000 wsgi:application
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes_from:
        - webappsource
    links:
        - database
    ports:
        - "8000:8000"

rabbitmq:
    image: rabbitmq:3

celery:
    image: celery:3
    links:
        - rabbitmq:rabbit
    volumes_from:
        - webappsource

# webserver:
#     build: webserver
#     ports:
#         - "80:80"
#         - "443:443"
#     links:
#         - webapp
