# coding: utf-8
from geoalchemy2 import Geometry
from sqlalchemy import BigInteger, Boolean, Column, DateTime, Float, Integer, SmallInteger, String, Table, Text
from sqlalchemy.dialects.postgresql.hstore import HSTORE
from sqlalchemy.sql.sqltypes import TEXT, BOOLEAN
from sqlalchemy.dialects.postgresql.base import ARRAY, DOUBLE_PRECISION
from sqlalchemy.ext.declarative import declarative_base


Base = declarative_base()
metadata = Base.metadata


t_geography_columns = Table(
    'geography_columns', metadata,
    Column('f_table_catalog', String),
    Column('f_table_schema', String),
    Column('f_table_name', String),
    Column('f_geography_column', String),
    Column('coord_dimension', Integer),
    Column('srid', Integer),
    Column('type', Text)
)


t_geometry_columns = Table(
    'geometry_columns', metadata,
    Column('f_table_catalog', String(256)),
    Column('f_table_schema', String),
    Column('f_table_name', String),
    Column('f_geometry_column', String),
    Column('coord_dimension', Integer),
    Column('srid', Integer),
    Column('type', String(30))
)


t_osm_line = Table(
    'osm_line', metadata,
    Column('osm_id', BigInteger),
    Column('access', Text),
    Column('addr:city', Text),
    Column('addr:housenumber', Text),
    Column('addr:interpolation', Text),
    Column('addr:place', Text),
    Column('addr:postcode', Text),
    Column('addr:street', Text),
    Column('addr:country', Text),
    Column('admin_level', Text),
    Column('aerialway', Text),
    Column('aeroway', Text),
    Column('amenity', Text),
    Column('area', Text),
    Column('barrier', Text),
    Column('brand', Text),
    Column('bridge', Text),
    Column('boundary', Text),
    Column('building', Text),
    Column('bus', Text),
    Column('contact:phone', Text),
    Column('cuisine', Text),
    Column('denomination', Text),
    Column('drinkable', Text),
    Column('emergency', Text),
    Column('entrance', Text),
    Column('foot', Text),
    Column('frequency', Text),
    Column('generator:source', Text),
    Column('height', Text),
    Column('highway', Text),
    Column('historic', Text),
    Column('information', Text),
    Column('junction', Text),
    Column('landuse', Text),
    Column('layer', Text),
    Column('leisure', Text),
    Column('man_made', Text),
    Column('maxspeed', Text),
    Column('military', Text),
    Column('name', Text),
    Column('int_name', Text),
    Column('name:en', Text),
    Column('name:de', Text),
    Column('name:fr', Text),
    Column('name:es', Text),
    Column('natural', Text),
    Column('office', Text),
    Column('oneway', Text),
    Column('opening_hours', Text),
    Column('operator', Text),
    Column('phone', Text),
    Column('power', Text),
    Column('power_source', Text),
    Column('parking', Text),
    Column('place', Text),
    Column('population', Text),
    Column('public_transport', Text),
    Column('recycling:glass', Text),
    Column('recycling:paper', Text),
    Column('recycling:clothes', Text),
    Column('recycling:scrap_metal', Text),
    Column('railway', Text),
    Column('ref', Text),
    Column('religion', Text),
    Column('route', Text),
    Column('service', Text),
    Column('shop', Text),
    Column('sport', Text),
    Column('tourism', Text),
    Column('tower:type', Text),
    Column('tracktype', Text),
    Column('traffic_calming', Text),
    Column('train', Text),
    Column('tram', Text),
    Column('tunnel', Text),
    Column('type', Text),
    Column('vending', Text),
    Column('voltage', Text),
    Column('water', Text),
    Column('waterway', Text),
    Column('website', Text),
    Column('wetland', Text),
    Column('width', Text),
    Column('wikipedia', Text),
    Column('z_order', SmallInteger),
    Column('way_area', Float),
    Column('osm_timestamp', DateTime),
    Column('osm_version', Text),
    Column('tags', HSTORE),
    Column('way', Geometry(geometry_type='LineString', srid=900913), index=True)
)


t_osm_point = Table(
    'osm_point', metadata,
    Column('osm_id', BigInteger),
    Column('access', Text),
    Column('addr:city', Text),
    Column('addr:housenumber', Text),
    Column('addr:interpolation', Text),
    Column('addr:place', Text),
    Column('addr:postcode', Text),
    Column('addr:street', Text),
    Column('addr:country', Text),
    Column('admin_level', Text),
    Column('aerialway', Text),
    Column('aeroway', Text),
    Column('amenity', Text),
    Column('area', Text),
    Column('barrier', Text),
    Column('brand', Text),
    Column('bridge', Text),
    Column('boundary', Text),
    Column('building', Text),
    Column('bus', Text),
    Column('contact:phone', Text),
    Column('cuisine', Text),
    Column('denomination', Text),
    Column('drinkable', Text),
    Column('ele', Text),
    Column('emergency', Text),
    Column('entrance', Text),
    Column('foot', Text),
    Column('frequency', Text),
    Column('generator:source', Text),
    Column('height', Text),
    Column('highway', Text),
    Column('historic', Text),
    Column('information', Text),
    Column('junction', Text),
    Column('landuse', Text),
    Column('layer', Text),
    Column('leisure', Text),
    Column('man_made', Text),
    Column('maxspeed', Text),
    Column('military', Text),
    Column('name', Text),
    Column('int_name', Text),
    Column('name:en', Text),
    Column('name:de', Text),
    Column('name:fr', Text),
    Column('name:es', Text),
    Column('natural', Text),
    Column('office', Text),
    Column('oneway', Text),
    Column('opening_hours', Text),
    Column('operator', Text),
    Column('phone', Text),
    Column('power', Text),
    Column('power_source', Text),
    Column('parking', Text),
    Column('place', Text),
    Column('population', Text),
    Column('public_transport', Text),
    Column('recycling:glass', Text),
    Column('recycling:paper', Text),
    Column('recycling:clothes', Text),
    Column('recycling:scrap_metal', Text),
    Column('railway', Text),
    Column('ref', Text),
    Column('religion', Text),
    Column('route', Text),
    Column('service', Text),
    Column('shop', Text),
    Column('sport', Text),
    Column('tourism', Text),
    Column('tower:type', Text),
    Column('traffic_calming', Text),
    Column('train', Text),
    Column('tram', Text),
    Column('tunnel', Text),
    Column('type', Text),
    Column('vending', Text),
    Column('voltage', Text),
    Column('water', Text),
    Column('waterway', Text),
    Column('website', Text),
    Column('wetland', Text),
    Column('width', Text),
    Column('wikipedia', Text),
    Column('z_order', SmallInteger),
    Column('osm_timestamp', DateTime),
    Column('osm_version', Text),
    Column('tags', HSTORE),
    Column('way', Geometry(geometry_type='Point', srid=900913), index=True)
)


t_osm_polygon = Table(
    'osm_polygon', metadata,
    Column('osm_id', BigInteger),
    Column('access', Text),
    Column('addr:city', Text),
    Column('addr:housenumber', Text),
    Column('addr:interpolation', Text),
    Column('addr:place', Text),
    Column('addr:postcode', Text),
    Column('addr:street', Text),
    Column('addr:country', Text),
    Column('admin_level', Text),
    Column('aerialway', Text),
    Column('aeroway', Text),
    Column('amenity', Text),
    Column('area', Text),
    Column('barrier', Text),
    Column('brand', Text),
    Column('bridge', Text),
    Column('boundary', Text),
    Column('building', Text),
    Column('bus', Text),
    Column('contact:phone', Text),
    Column('cuisine', Text),
    Column('denomination', Text),
    Column('drinkable', Text),
    Column('emergency', Text),
    Column('entrance', Text),
    Column('foot', Text),
    Column('frequency', Text),
    Column('generator:source', Text),
    Column('height', Text),
    Column('highway', Text),
    Column('historic', Text),
    Column('information', Text),
    Column('junction', Text),
    Column('landuse', Text),
    Column('layer', Text),
    Column('leisure', Text),
    Column('man_made', Text),
    Column('maxspeed', Text),
    Column('military', Text),
    Column('name', Text),
    Column('int_name', Text),
    Column('name:en', Text),
    Column('name:de', Text),
    Column('name:fr', Text),
    Column('name:es', Text),
    Column('natural', Text),
    Column('office', Text),
    Column('oneway', Text),
    Column('opening_hours', Text),
    Column('operator', Text),
    Column('phone', Text),
    Column('power', Text),
    Column('power_source', Text),
    Column('parking', Text),
    Column('place', Text),
    Column('population', Text),
    Column('public_transport', Text),
    Column('recycling:glass', Text),
    Column('recycling:paper', Text),
    Column('recycling:clothes', Text),
    Column('recycling:scrap_metal', Text),
    Column('railway', Text),
    Column('ref', Text),
    Column('religion', Text),
    Column('route', Text),
    Column('service', Text),
    Column('shop', Text),
    Column('sport', Text),
    Column('tourism', Text),
    Column('tower:type', Text),
    Column('tracktype', Text),
    Column('traffic_calming', Text),
    Column('train', Text),
    Column('tram', Text),
    Column('tunnel', Text),
    Column('type', Text),
    Column('vending', Text),
    Column('voltage', Text),
    Column('water', Text),
    Column('waterway', Text),
    Column('website', Text),
    Column('wetland', Text),
    Column('width', Text),
    Column('wikipedia', Text),
    Column('z_order', SmallInteger),
    Column('way_area', Float),
    Column('osm_timestamp', DateTime),
    Column('osm_version', Text),
    Column('tags', HSTORE),
    Column('way', Geometry(geometry_type='Geometry', srid=900913), index=True)
)


t_osm_roads = Table(
    'osm_roads', metadata,
    Column('osm_id', BigInteger),
    Column('access', Text),
    Column('addr:city', Text),
    Column('addr:housenumber', Text),
    Column('addr:interpolation', Text),
    Column('addr:place', Text),
    Column('addr:postcode', Text),
    Column('addr:street', Text),
    Column('addr:country', Text),
    Column('admin_level', Text),
    Column('aerialway', Text),
    Column('aeroway', Text),
    Column('amenity', Text),
    Column('area', Text),
    Column('barrier', Text),
    Column('brand', Text),
    Column('bridge', Text),
    Column('boundary', Text),
    Column('building', Text),
    Column('bus', Text),
    Column('contact:phone', Text),
    Column('cuisine', Text),
    Column('denomination', Text),
    Column('drinkable', Text),
    Column('emergency', Text),
    Column('entrance', Text),
    Column('foot', Text),
    Column('frequency', Text),
    Column('generator:source', Text),
    Column('height', Text),
    Column('highway', Text),
    Column('historic', Text),
    Column('information', Text),
    Column('junction', Text),
    Column('landuse', Text),
    Column('layer', Text),
    Column('leisure', Text),
    Column('man_made', Text),
    Column('maxspeed', Text),
    Column('military', Text),
    Column('name', Text),
    Column('int_name', Text),
    Column('name:en', Text),
    Column('name:de', Text),
    Column('name:fr', Text),
    Column('name:es', Text),
    Column('natural', Text),
    Column('office', Text),
    Column('oneway', Text),
    Column('opening_hours', Text),
    Column('operator', Text),
    Column('phone', Text),
    Column('power', Text),
    Column('power_source', Text),
    Column('parking', Text),
    Column('place', Text),
    Column('population', Text),
    Column('public_transport', Text),
    Column('recycling:glass', Text),
    Column('recycling:paper', Text),
    Column('recycling:clothes', Text),
    Column('recycling:scrap_metal', Text),
    Column('railway', Text),
    Column('ref', Text),
    Column('religion', Text),
    Column('route', Text),
    Column('service', Text),
    Column('shop', Text),
    Column('sport', Text),
    Column('tourism', Text),
    Column('tower:type', Text),
    Column('tracktype', Text),
    Column('traffic_calming', Text),
    Column('train', Text),
    Column('tram', Text),
    Column('tunnel', Text),
    Column('type', Text),
    Column('vending', Text),
    Column('voltage', Text),
    Column('water', Text),
    Column('waterway', Text),
    Column('website', Text),
    Column('wetland', Text),
    Column('width', Text),
    Column('wikipedia', Text),
    Column('z_order', SmallInteger),
    Column('way_area', Float),
    Column('osm_timestamp', DateTime),
    Column('osm_version', Text),
    Column('tags', HSTORE),
    Column('way', Geometry(geometry_type='LineString', srid=900913), index=True)
)


t_raster_columns = Table(
    'raster_columns', metadata,
    Column('r_table_catalog', String),
    Column('r_table_schema', String),
    Column('r_table_name', String),
    Column('r_raster_column', String),
    Column('srid', Integer),
    Column('scale_x', Float(53)),
    Column('scale_y', Float(53)),
    Column('blocksize_x', Integer),
    Column('blocksize_y', Integer),
    Column('same_alignment', Boolean),
    Column('regular_blocking', Boolean),
    Column('num_bands', Integer),
    Column('pixel_types', ARRAY(TEXT())),
    Column('nodata_values', ARRAY(DOUBLE_PRECISION(precision=53))),
    Column('out_db', ARRAY(BOOLEAN())),
    Column('extent', Geometry),
    Column('spatial_index', Boolean)
)


t_raster_overviews = Table(
    'raster_overviews', metadata,
    Column('o_table_catalog', String),
    Column('o_table_schema', String),
    Column('o_table_name', String),
    Column('o_raster_column', String),
    Column('r_table_catalog', String),
    Column('r_table_schema', String),
    Column('r_table_name', String),
    Column('r_raster_column', String),
    Column('overview_factor', Integer)
)


class SpatialRefSy(Base):
    __tablename__ = 'spatial_ref_sys'

    srid = Column(Integer, primary_key=True)
    auth_name = Column(String(256))
    auth_srid = Column(Integer)
    srtext = Column(String(2048))
    proj4text = Column(String(2048))
