# Generated by Django 3.2.6 on 2021-08-19 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0004_auto_20160310_1102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='site',
            options={'ordering': ['domain'], 'verbose_name': 'site', 'verbose_name_plural': 'sites'},
        ),
    ]
