# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-21 14:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excerptexport', '0020_export_status'),
        ('excerptexport', '0020_change_export_file_format_from_TextField_to_CharField'),
    ]

    operations = [
    ]
