# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-06 04:47
from __future__ import unicode_literals

from django.db import migrations


def remove_stale_extraction_orders_and_stale_excerpts(apps, schema_editor):
    ExtractionOrder = apps.get_model('excerptexport', 'ExtractionOrder')  # noqa
    Excerpt = apps.get_model('excerptexport', 'Excerpt')  # noqa
    ExtractionOrder.objects.filter(excerpt__isnull=True).delete()
    Excerpt.objects.filter(extraction_orders__isnull=True).delete()


def no_need_to_add_stale_data_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('excerptexport', '0029_remove_extractionorder_country_id'),
    ]

    operations = [
        migrations.RunPython(
            remove_stale_extraction_orders_and_stale_excerpts,
            no_need_to_add_stale_data_reverse
        )
    ]
