# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 13:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excerptexport', '0039_auto_20160528_1132'),
        ('excerptexport', '0039_update_countries_20160528_2049'),
    ]

    operations = [
    ]
