# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-19 12:58
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excerptexport', '0055_auto_20160713_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excerpt',
            name='bounding_geometry',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(default='MULTIPOLYGON EMPTY', srid=4326, verbose_name='bounding geometry'),
            preserve_default=False,
        ),
    ]
