# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-11 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excerptexport', '0056_auto_20160919_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='export',
            name='file_format',
            field=models.CharField(choices=[('fgdb', 'Esri File Geodatabase'), ('shapefile', 'Esri Shapefile'), ('gpkg', 'GeoPackage'), ('spatialite', 'SpatiaLite'), ('garmin', 'Garmin navigation & map data'), ('pbf', 'OSM Protocolbuffer Binary Format')], max_length=10, verbose_name='file format / data format'),
        ),
    ]
