# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-11 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excerptexport', '0057_auto_20170511_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='export',
            name='status',
            field=models.CharField(choices=[('received', 'received'), ('queued', 'queued'), ('finished', 'finished'), ('failed', 'failed'), ('started', 'started'), ('deferred', 'deferred')], default=None, max_length=20, null=True, verbose_name='job status'),
        ),
    ]
