# Generated by Django 3.2.6 on 2021-08-31 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excerptexport', '0062_auto_20210831_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractionorder',
            name='email_sent',
            field=models.BooleanField(default=False, verbose_name='email sent'),
        ),
        migrations.AddField(
            model_name='extractionorder',
            name='export_finished',
            field=models.BooleanField(default=False, verbose_name='export finished'),
        ),
    ]
