# Generated by Django 3.2.6 on 2021-09-01 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excerptexport', '0065_auto_20210901_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractionorder',
            name='assigned_task_id',
            field=models.CharField(max_length=200, null=True, verbose_name='assigned task id'),
        ),
    ]
