# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-16 13:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='token_creation_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 16, 13, 56, 28, 104301, tzinfo=utc), verbose_name='token timestamp'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='unverified_email',
            field=models.EmailField(max_length=200, null=True, verbose_name='unverified email'),
        ),
    ]
