# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-17 14:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_auto_20160816_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='token_creation_time',
        ),
    ]
