# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-04 18:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excerptexport', '0026_auto_20160504_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bboxboundinggeometry',
            name='boundinggeometry_ptr',
        ),
        migrations.RemoveField(
            model_name='osmosispolygonfilterboundinggeometry',
            name='boundinggeometry_ptr',
        ),
        migrations.RemoveField(
            model_name='excerpt',
            name='bounding_geometry_old',
        ),
        migrations.DeleteModel(
            name='BBoxBoundingGeometry',
        ),
        migrations.DeleteModel(
            name='BoundingGeometry',
        ),
        migrations.DeleteModel(
            name='OsmosisPolygonFilterBoundingGeometry',
        ),
    ]
