# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 20:35
from __future__ import unicode_literals

from django.db import migrations


def timestamp_export(apps, schema_editor):
    Export = apps.get_model("excerptexport", "Export")  # noqa
    for export in Export.objects.filter(updated_at__isnull=True):
        export.updated_at = export.created_at
        export.save()


def reverse_timestamp_export(apps, schema_editor):
    # no need for reversing this, but easier if a backwards migration exists
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('excerptexport', '0040_merge'),
    ]

    operations = [
        migrations.RunPython(timestamp_export, reverse_timestamp_export)
    ]
