# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 13:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excerptexport', '0041_set_date_to_past_for_existing_exports_20160531_2235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outputfile',
            name='file_extension',
        ),
    ]
