# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-08 13:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excerptexport', '0043_extractionorder_coordinate_reference_system'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extractionorder',
            name='_extraction_configuration',
        ),
    ]
