# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excerptexport', '0053_rename_pseudo-mercator_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='export',
            name='file_format',
            field=models.CharField(choices=[('fgdb', 'Esri File Geodatabase'), ('shapefile', 'Esri Shapefile'), ('gpkg', 'GeoPackage'), ('spatialite', 'SpatiaLite'), ('garmin', 'Garmin navigation & map data')], max_length=10, verbose_name='file format / data format'),
        ),
    ]
