# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excerptexport', '0054_rename_ESRI_to_Esri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractionorder',
            name='detail_level',
            field=models.IntegerField(choices=[(120, 'Full detail'), (60, 'Simplified')], default=120, verbose_name='detail level'),
        ),
    ]
