# Generated by Django 3.2.6 on 2021-08-31 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excerptexport', '0060_auto_20210819_0910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='export',
            name='conversion_service_job_id',
        ),
        migrations.RemoveField(
            model_name='extractionorder',
            name='process_id',
        ),
        migrations.RemoveField(
            model_name='extractionorder',
            name='progress_url',
        ),
        migrations.AlterField(
            model_name='export',
            name='status',
            field=models.CharField(choices=[('received', 'received'), ('queued', 'queued'), ('finished', 'finished'), ('failed', 'failed'), ('started', 'started'), ('deferred', 'deferred')], default='received', max_length=20, null=True, verbose_name='job status'),
        ),
    ]
