# Generated by Django 3.2.6 on 2021-08-31 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excerptexport', '0061_auto_20210831_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='export',
            name='estimated_pbf_size',
            field=models.FloatField(null=True, verbose_name='estimated pbf size in bytes'),
        ),
        migrations.AddField(
            model_name='export',
            name='extraction_duration',
            field=models.DurationField(help_text='time needed to generate the extraction', null=True, verbose_name='extraction duration'),
        ),
        migrations.AddField(
            model_name='export',
            name='unzipped_result_size',
            field=models.FloatField(help_text='without the static files, only the conversion result', null=True, verbose_name='file size in bytes'),
        ),
    ]
