# Generated by Django 4.1.7 on 2023-03-14 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("excerptexport", "0066_extractionorder_assigned_task_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="export",
            name="file_format",
            field=models.CharField(
                choices=[
                    ("shapefile", "Esri Shapefile"),
                    ("gpkg", "GeoPackage"),
                    ("spatialite", "SpatiaLite"),
                    ("garmin", "Garmin navigation & map data"),
                    ("pbf", "OSM Protocolbuffer Binary Format"),
                ],
                max_length=10,
                verbose_name="file format / data format",
            ),
        ),
    ]
