# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excerptexport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractionorder',
            name='state',
            field=models.IntegerField(default=0, verbose_name='state'),
        ),
    ]
