# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-19 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excerptexport', '0019_one_export_per_file_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='export',
            name='status',
            field=models.CharField(choices=[('initial', 'initial'), ('received', 'received'), ('queued', 'queued'), ('finished', 'finished'), ('failed', 'failed'), ('started', 'started'), ('deferred', 'deferred')], default='initial', max_length=20, verbose_name='job status'),
        ),
    ]
