# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-14 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excerptexport', '0019_one_export_per_file_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='export',
            name='conversion_service_job_id',
            field=models.IntegerField(null=True, verbose_name='conversion service job ID'),
        ),
    ]
