# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-25 14:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('excerptexport', '0021_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='outputfile',
            name='export',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='output_file', to='excerptexport.Export', verbose_name='export'),
        ),
    ]
