# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-27 07:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('excerptexport', '0022_transfer_output_files_from_extraction_orders_to_exports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outputfile',
            name='export',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='output_file', to='excerptexport.Export', verbose_name='export'),
        ),
    ]
