# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-25 14:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excerptexport', '0023_populate_ouput_file_export'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outputfile',
            name='extraction_order',
        ),
    ]
