# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-26 14:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excerptexport', '0024_remove_outputfile_extraction_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outputfile',
            name='file_extension',
        ),
    ]
