# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-06 04:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excerptexport', '0027_auto_20160504_2058'),
    ]

    operations = []
