# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-06 04:47
from __future__ import unicode_literals

from django.db import migrations


def move_country_from_extraction_order_to_export(apps, schema_editor):
    Excerpt = apps.get_model('excerptexport', 'Excerpt')  # noqa
    ExtractionOrder = apps.get_model('excerptexport', 'ExtractionOrder')  # noqa
    Country = apps.get_model('countries', 'Country')  # noqa

    for extraction_order in ExtractionOrder.objects.filter(country_id__isnull=False):
        country = Country.objects.get(pk=extraction_order.country_id)
        extraction_order.country_id = None
        excerpt = Excerpt.objects.create(
            name=country.name,
            country=country,
            owner=extraction_order.orderer
        )
        excerpt.save()
        extraction_order.save()


def move_country_from_extraction_order_to_export_undo(apps, schema_editor):
    Excerpt = apps.get_model('excerptexport', 'Excerpt')  # noqa
    for excerpt in Excerpt.objects.all():
        if excerpt.country is not None:
            country = excerpt.country
            for extraction_order in excerpt.extraction_orders.all():
                extraction_order.country_id = country.id
                extraction_order.save()
            excerpt.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('excerptexport', '0027_auto_20160504_2058'),
        ('countries', '0003_auto_20160310_1124'),
    ]

    operations = [
        migrations.RunPython(
            move_country_from_extraction_order_to_export, move_country_from_extraction_order_to_export_undo
        )
    ]
