# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-06 05:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excerptexport', '0028_move_country_to_excerpt_20160506_0647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extractionorder',
            name='country_id',
        ),
    ]
