# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 11:07
from __future__ import unicode_literals

from django.db import migrations, models

COUNTRY_TYPE = 'country'
USER_DEFINED_TYPE = 'user-defined'


def set_correct_type(apps, schema_editor):
    Excerpt = apps.get_model('excerptexport', 'Excerpt')  # noqa
    for excerpt in Excerpt.objects.filter(bounding_geometry__isnull=True):
        excerpt.excerpt_type = COUNTRY_TYPE
        excerpt.save()


def reset_type_to_default(apps, schema_editor):
    Excerpt = apps.get_model('excerptexport', 'Excerpt')  # noqa
    for excerpt in Excerpt.objects.filter(bounding_geometry__isnull=True):
        excerpt.excerpt_type = USER_DEFINED_TYPE
        excerpt.save()


class Migration(migrations.Migration):
    dependencies = [
        ('excerptexport', '0030_remove_empty_exports_20160519_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='excerpt',
            name='excerpt_type',
            field=models.CharField(choices=[(USER_DEFINED_TYPE, 'user defined'), (COUNTRY_TYPE, 'country')], default=USER_DEFINED_TYPE, max_length=40),
        ),
        migrations.RunPython(
            set_correct_type, reset_type_to_default
        )
    ]
