# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 11:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('excerptexport', '0031_add_types_field_20160518_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excerpt',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='excerpts', to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
    ]
