# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 12:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excerptexport', '0030_auto_20160517_1339'),
        ('excerptexport', '0034_auto_20160519_0825'),
    ]

    operations = [
    ]
