# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-23 11:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excerptexport', '0036_move_download_files_to_new_field_20160520_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outputfile',
            name='file_old',
        ),
    ]
