# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-10 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excerptexport', '0044_remove_extractionorder__extraction_configuration'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractionorder',
            name='detail_level',
            field=models.IntegerField(choices=[(120, 'Complete'), (60, 'Simplified')], default=120, verbose_name='detail level'),
        ),
    ]
