# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excerptexport', '0047_auto_20160613_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='outputfile',
            name='file_removal_at',
            field=models.DateTimeField(blank=True, default=None, editable=False, null=True, verbose_name='file removal date'),
        ),
    ]
