# Generated by Django 3.2.6 on 2021-09-01 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excerptexport', '0063_auto_20210831_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractionorder',
            name='invoke_update_url',
            field=models.URLField(default='http://localhost:8000', max_length=250, verbose_name='url to invoke for updates'),
        ),
    ]
