version: '3.8'
# for local development

# to run python tests:
# docker-compose run --rm -e DJANGO_SETTINGS_MODULE=config.settings django  python manage.py test

services:
  ##### frontend START ########
  tests:
    image: geometalab/osmaxx-frontend:latest
    build:
      context: ..
      dockerfile: Dockerfile
      target: worker
    command: pytest
    user: "1000"
    working_dir: /home/py/osmaxx
    volumes:
      - ../osmaxx:/home/py/osmaxx/osmaxx
      - ../tests:/home/py/osmaxx/tests
      - ../web_frontend:/home/py/osmaxx/web_frontend
    environment: &baseenv
      ? DJANGO_ALLOWED_HOSTS=*
      ? DJANGO_SECRET_KEY=insecure!1
      ? DJANGO_DEBUG=true
      ? DJANGO_CSRF_COOKIE_SECURE=false
      ? DJANGO_SESSION_COOKIE_SECURE=false
      ? DJANGO_DATABASE_URL=postgis://testuser:test@testdb/test
      ? CELERY_BROKER_URL=redis://redis:6379/1
      ? PG_TRANSLIT_HOST=testdb
      ? DJANGO_DB_HOST=testdb
      ? DJANGO_DB_PORT=5432
    networks:
      - default
    logging: &logging
      driver: json-file
      options:
        max-size: 50m
  testdb:
    image: postgis/postgis:15-3.3
    volumes:
      - database-data:/database/data
    environment:
      - PGDATA=/database/data/db
      - POSTGRES_DB=test
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=test
    networks:
      - default
    logging:
      <<: *logging
  redis:
    image: redis
    networks:
      - default
    logging:
      <<: *logging
volumes:
  # osmaxx
  database-data: {}
