# Generated by Django 3.2.6 on 2021-08-19 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clipping_area', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clippingarea',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
